In [1]:
import numpy as np
List = ["x_1","x_2","x_3","x_4","x_5","x_6","x_7","x_8","x_9"," x_10"] 
Table = []
Table_1 = []

for i_1 in range(10):
  for i_2 in range(10):
    List[i_2] = i_2*10 + i_1
    Table.append(List[i_2])
  Table_1.append(Table)
  Table = []

Data = np.array([Table_1[0],Table_1[9],Table_1[2],Table_1[7],Table_1[4],Table_1[5],Table_1[6],Table_1[3],Table_1[8],Table_1[1]])

Data_2 = []
Data_3 = []

for j_1 in range(10):
  for j_2 in range(10):
    Data_1 = Data[j_2][j_1]
    Data_2.append(Data_1)
  Data_3.append(Data_2)
  Data_2 = []
Ans = np.array(Data_3)

print(Ans)

[[ 0  9  2  7  4  5  6  3  8  1]
 [10 19 12 17 14 15 16 13 18 11]
 [20 29 22 27 24 25 26 23 28 21]
 [30 39 32 37 34 35 36 33 38 31]
 [40 49 42 47 44 45 46 43 48 41]
 [50 59 52 57 54 55 56 53 58 51]
 [60 69 62 67 64 65 66 63 68 61]
 [70 79 72 77 74 75 76 73 78 71]
 [80 89 82 87 84 85 86 83 88 81]
 [90 99 92 97 94 95 96 93 98 91]]


In [2]:
Dict = {
    "name" : "ABCD",
    "age" : 18,
    "gender" : "Man",
    "like" : ["dog","cat","fish"]
}
print(Dict.keys())
print(Dict.values())

dict_keys(['name', 'age', 'gender', 'like'])
dict_values(['ABCD', 18, 'Man', ['dog', 'cat', 'fish']])


In [3]:
Dict["name"] = "Boss"
Dict.update({"like" : ["game","catoon"]})
Dict.update({"colour" : "back"})
Dict.update({"food" : {"sweet" : "cake"}})
print(Dict)

{'name': 'Boss', 'age': 18, 'gender': 'Man', 'like': ['game', 'catoon'], 'colour': 'back', 'food': {'sweet': 'cake'}}


In [4]:
jane = {
  "people" : [{"firstName": "Joe","lastName": "Jackson","gender": "male","age": 28,"number": "7349282382"},
    {"firstName": "James","lastName": "Smith","gender": "male","age": 32,"number": "5678568567"},
    {"firstName": "Emily","lastName": "Jones","gender": "female","age": 24,"number": "456754675"}]
}

Round_1 = jane["people"]

for x_0 in range(3):
  for x_1 in Round_1[x_0]:
    if x_1 in Round_1[x_0]:
      if Round_1[x_0][x_1] in Round_1[x_0].values():
        print(x_1,end=" ")
        print(Round_1[0][x_1])

firstName Joe
lastName Jackson
gender male
age 28
number 7349282382
firstName Joe
lastName Jackson
gender male
age 28
number 7349282382
firstName Joe
lastName Jackson
gender male
age 28
number 7349282382


In [5]:
import pandas as pd
List_1 = [1,2,3,4,5,6,7]
s = pd.Series(List_1,index=[7,6,5,4,3,2,1])
s

7    1
6    2
5    3
4    4
3    5
2    6
1    7
dtype: int64

In [13]:
import json
Open = open("lingmaichobcomputer.json")
Data = json.load(Open)
D = {"Data":Data}
D = pd.DataFrame(D)
D

Data
Calories  {'0': 409.1, '1': 479.0, '2': 340.0, '3': 282....
Duration  {'0': 60, '1': 60, '2': 60, '3': 45, '4': 45, ...
Maxpulse  {'0': 130, '1': 145, '2': 135, '3': 175, '4': ...
Pulse     {'0': 110, '1': 117, '2': 103, '3': 109, '4': ...