In [23]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np

In [24]:
df = sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [25]:
feature = df.drop('species', axis=1)
labels = df.species

In [26]:
feature_train, feature_test, labels_train, labels_test = train_test_split(feature, labels, test_size=0.3)
(label, count) = np.unique(labels_test, return_counts=True)
freq = np.asarray((label, count)).T
freq

array([['setosa', 15],
       ['versicolor', 17],
       ['virginica', 13]], dtype=object)

In [27]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [28]:
from sklearn.svm import SVC

model = SVC(kernel='linear')
model.fit(feature_train, labels_train)
labels_pred = model.predict(feature_test)

In [29]:
print('Accuracy Score : {:.4f}'.format(accuracy_score(labels_test, labels_pred)))
print(classification_report(labels_test, labels_pred))
cm = confusion_matrix(labels_test, labels_pred)
print(cm)

Accuracy Score : 0.9556
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      0.88      0.94        17
   virginica       0.87      1.00      0.93        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[15  0  0]
 [ 0 15  2]
 [ 0  0 13]]
